apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: triton
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: Prune=true
spec:
  project: default
  source:
    repoURL: https://github.com/salilkadam/Infrastructure.git
    targetRevision: HEAD
    path: applications/triton/base
  destination:
    server: https://kubernetes.default.svc
    namespace: triton
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  revisionHistoryLimit: 10

