apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  labels:
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/part-of: infrastructure
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@askcollections.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx 