apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: monitoring-base

resources:
- namespace.yaml
- rbac.yaml
- prometheus-config.yaml
- prometheus.yaml
- grafana.yaml
- grafana-datasources.yaml
- grafana-dashboards.yaml
- node-exporter.yaml
- postgres-exporter.yaml
- ingress.yaml
- cluster-issuer.yaml
- dcgm-exporter.yaml

commonLabels:
  app.kubernetes.io/part-of: infrastructure

patches:
- target:
    kind: Deployment
    name: grafana
  patch: |-
    - op: replace
      path: /metadata/labels/app.kubernetes.io~1name
      value: grafana
    - op: replace
      path: /spec/selector/matchLabels/app.kubernetes.io~1name
      value: grafana
    - op: replace
      path: /spec/template/metadata/labels/app.kubernetes.io~1name
      value: grafana
- target:
    kind: Service
    name: grafana
  patch: |-
    - op: replace
      path: /metadata/labels/app.kubernetes.io~1name
      value: grafana
    - op: replace
      path: /spec/selector/app.kubernetes.io~1name
      value: grafana
- target:
    kind: Deployment
    name: postgres-exporter
  patch: |-
    - op: replace
      path: /metadata/labels/app.kubernetes.io~1name
      value: postgres-exporter
    - op: replace
      path: /spec/selector/matchLabels/app.kubernetes.io~1name
      value: postgres-exporter
    - op: replace
      path: /spec/template/metadata/labels/app.kubernetes.io~1name
      value: postgres-exporter
- target:
    kind: Service
    name: postgres-exporter
  patch: |-
    - op: replace
      path: /metadata/labels/app.kubernetes.io~1name
      value: postgres-exporter
    - op: replace
      path: /spec/selector/app.kubernetes.io~1name
      value: postgres-exporter 