apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg-prod
  namespace: argocd
  labels:
    app.kubernetes.io/name: cloudnative-pg
    app.kubernetes.io/part-of: infrastructure
    environment: production
spec:
  project: default
  source:
    repoURL: https://github.com/salilkadam/Infrastructure.git
    targetRevision: HEAD
    path: applications/cloudnative-pg/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  revisionHistoryLimit: 10 