apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg-staging
  namespace: argocd
  labels:
    app.kubernetes.io/name: cloudnative-pg
    app.kubernetes.io/part-of: infrastructure
    environment: staging
spec:
  project: default
  source:
    repoURL: https://github.com/salilkadam/Infrastructure.git
    targetRevision: HEAD
    path: applications/cloudnative-pg/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  revisionHistoryLimit: 10 