apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- target:
    kind: PersistentVolumeClaim
    name: minio-storage
  patch: |-
    - op: replace
      path: /spec/resources/requests/storage
      value: 200Gi

- target:
    kind: Deployment
    name: minio-deployment
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: "512Mi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: "500m"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: "1Gi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: "1000m"

- target:
    kind: Ingress
    name: minio-ingress
  patch: |-
    - op: replace
      path: /metadata/annotations/cert-manager.io~1cluster-issuer
      value: "letsencrypt-prod"
    - op: add
      path: /metadata/annotations/nginx.ingress.kubernetes.io~1backend-protocol
      value: "HTTPS"
    - op: add
      path: /metadata/annotations/nginx.ingress.kubernetes.io~1proxy-ssl-verify
      value: "off"
    - op: replace
      path: /spec/rules/0/host
      value: minio.askcollections.com
    - op: replace
      path: /spec/tls/0/hosts/0
      value: minio.askcollections.com

- target:
    kind: Certificate
    name: minio-internal-ca
  patch: |-
    - op: replace
      path: /spec/issuerRef/name
      value: "prod-minio-selfsigned-clusterissuer-prod"

- target:
    kind: Certificate
    name: minio-internal-tls
  patch: |-
    - op: replace
      path: /spec/issuerRef/name
      value: "prod-minio-internal-ca-issuer-prod"

namePrefix: prod-
nameSuffix: -prod 