apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- target:
    kind: PersistentVolumeClaim
    name: minio-storage
  patch: |-
    - op: replace
      path: /spec/resources/requests/storage
      value: 200Gi

- target:
    kind: Deployment
    name: minio-deployment
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 2
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: "512Mi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: "500m"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: "1Gi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: "1000m"

- target:
    kind: Ingress
    name: minio-ingress
  patch: |-
    - op: replace
      path: /metadata/annotations/cert-manager.io~1cluster-issuer
      value: "letsencrypt-prod"
    - op: replace
      path: /spec/rules/0/host
      value: minio-prod.example.com
    - op: replace
      path: /spec/rules/1/host
      value: minio-console-prod.example.com
    - op: replace
      path: /spec/tls/0/hosts/0
      value: minio-prod.example.com
    - op: replace
      path: /spec/tls/0/hosts/1
      value: minio-console-prod.example.com

- target:
    kind: ConfigMap
    name: minio-config
  patch: |-
    - op: replace
      path: /data/MINIO_BROWSER_REDIRECT_URL
      value: "https://minio-prod.example.com"
    - op: replace
      path: /data/MINIO_SERVER_URL
      value: "https://minio-prod.example.com"

namePrefix: prod-
nameSuffix: -prod 