apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- target:
    kind: StatefulSet
    name: minio
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 4
    - op: replace
      path: /spec/serviceName
      value: "prod-minio-hl-prod"
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: "1Gi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: "1000m"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: "2Gi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: "2000m"
    - op: replace
      path: /spec/volumeClaimTemplates/0/spec/resources/requests/storage
      value: 100Gi

- target:
    kind: Ingress
    name: minio-ingress
  patch: |-
    - op: replace
      path: /metadata/annotations/cert-manager.io~1cluster-issuer
      value: "letsencrypt-prod"
    - op: replace
      path: /spec/rules/0/host
      value: minio.askcollections.com
    - op: replace
      path: /spec/tls/0/hosts/0
      value: minio.askcollections.com

- target:
    kind: Certificate
    name: minio-internal-ca
  patch: |-
    - op: replace
      path: /spec/issuerRef/name
      value: "prod-minio-selfsigned-clusterissuer-prod"

- target:
    kind: Certificate
    name: minio-internal-tls
  patch: |-
    - op: replace
      path: /spec/issuerRef/name
      value: "prod-minio-internal-ca-issuer-prod"

namePrefix: prod-
nameSuffix: -prod 