apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-workspace-pvc
  namespace: dev-environment
  labels:
    app.kubernetes.io/name: dev-environment
    app.kubernetes.io/component: development
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-client 