apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: milvus
  namespace: argocd
  labels:
    app.kubernetes.io/name: milvus
    app.kubernetes.io/part-of: milvus
spec:
  project: default
  source:
    repoURL: https://github.com/salilkadam/Infrastructure.git
    targetRevision: HEAD
    path: applications/milvus/base
  destination:
    server: https://kubernetes.default.svc
    namespace: milvus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  revisionHistoryLimit: 10 