apiVersion: v1
kind: Namespace
metadata:
  name: milvus
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: milvus
  labels:
    app.kubernetes.io/name: milvus
    app.kubernetes.io/component: object-storage
    app.kubernetes.io/part-of: infrastructure
type: Opaque
data:
  accesskey: Y2MzYkdDckVZODdkU3Z2WGdreXk=
  secretkey: MFdzMjloM0tkUzNEdWpKZnFNZmpIQjZjUkpnUGJlbmxqeXhzZVhBago=
---
apiVersion: v1
kind: Service
metadata:
  name: milvus-service
  namespace: milvus
spec:
  ports:
    - port: 19530
      targetPort: 19530
      name: grpc
    - port: 19121
      targetPort: 19121
      name: http
  selector:
    app: milvus
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: milvus-pvc
  namespace: milvus
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 50Gi 