apiVersion: v1
kind: Secret
metadata:
  name: etcd
  namespace: etcd
  labels:
    app.kubernetes.io/name: etcd
    app.kubernetes.io/instance: etcd
type: Opaque
data:
  etcd-root-password: Y0JScHU4bUxFaw==  # cBRpu8mLEk 