apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: cloudnative-pg-prod

namespace: postgres

resources:
- ../../base

patches:
- target:
    kind: Cluster
    name: pg
  patch: |-
    - op: replace
      path: /spec/instances
      value: 3
    - op: replace
      path: /spec/resources/requests/memory
      value: "1Gi"
    - op: replace
      path: /spec/resources/requests/cpu
      value: "500m"
    - op: replace
      path: /spec/resources/limits/memory
      value: "2Gi"
    - op: replace
      path: /spec/resources/limits/cpu
      value: "2000m"
    - op: replace
      path: /spec/storage/size
      value: "50Gi"
    - op: replace
      path: /spec/postgresql/parameters/max_connections
      value: "200"
    - op: replace
      path: /spec/postgresql/parameters/shared_buffers
      value: "512MB"
    - op: replace
      path: /spec/postgresql/parameters/effective_cache_size
      value: "2GB"
    - op: replace
      path: /spec/postgresql/parameters/maintenance_work_mem
      value: "128MB"
    - op: replace
      path: /spec/postgresql/parameters/work_mem
      value: "8MB"
- target:
    kind: Deployment
    name: adminer
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 2
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: "128Mi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: "50m"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: "256Mi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: "200m" 