apiVersion: v1
kind: ConfigMap
metadata:
  name: milvus-config
  namespace: milvus
  labels:
    app.kubernetes.io/name: milvus
    app.kubernetes.io/part-of: milvus
data:
  milvus.yaml: |
    # etcd configuration
    etcd:
      endpoints:
        - http://etcd.etcd.svc.cluster.local:2379
      ssl:
        enabled: false
      username: "{{ ETCD_USERNAME }}"
      password: "{{ ETCD_PASSWORD }}"
    metastore:
      type: etcd

    # S3/MinIO configuration
    minio:
      address: minio-api.minio.svc.cluster.local
      port: 9000
      accessKeyID: "{{ MINIO_ACCESS_KEY }}"
      secretAccessKey: "{{ MINIO_SECRET_KEY }}"
      useSSL: true
      bucketName: milvus
      rootPath: file
      useIAM: false
      cloudProvider: 
      iamEndpoint: 

    # Data coordinator
    dataCoord:
      address: milvus-data-coordinator
      port: 19530

    # Root coordinator
    rootCoord:
      address: milvus-root-coordinator
      port: 19530

    # Index coordinator
    indexCoord:
      address: milvus-index-coordinator
      port: 19530

    # Query coordinator
    queryCoord:
      address: milvus-query-coordinator
      port: 19530

    # Data node
    dataNode:
      port: 19530

    # Index node
    indexNode:
      port: 19530

    # Query node
    queryNode:
      port: 19530

    proxy:
      port: 19530
      accessLog:
        localPath: /dev
        filename: stdout
      http:
        enabled: true

    # Log configuration
    log:
      level: info
      stdout: true

    # Common configuration
    common:
      storageType: minio
      security:
        authorizationEnabled: false 