apiVersion: v1
kind: ConfigMap
metadata:
  name: milvus-config
  namespace: milvus
  labels:
    app.kubernetes.io/name: milvus
    app.kubernetes.io/part-of: milvus
data:
  milvus.yaml: |
    etcd:
      endpoints:
        - http://etcd.etcd.svc.cluster.local:2379
      rootPath: milvus-dev
      auth:
        enabled: true
        userName: "root"
        password: "cBRpu8mLEk"
      ssl:
        enabled: false
    minio:
      address: minio-api.minio.svc.cluster.local
      port: 9000
      accessKeyID: "{{ MINIO_ACCESS_KEY }}"
      secretAccessKey: "{{ MINIO_SECRET_KEY }}"
      useSSL: true
      bucketName: milvus
      rootPath: file
    mq:
      type: pulsar
      pulsar:
        address: "pulsar://pulsar-service.pulsar.svc.cluster.local:6650"
        webAddress: "http://pulsar-service.pulsar.svc.cluster.local:8080"
        maxMessageSize: 5242880

    # Data coordinator
    dataCoord:
      address: milvus-data-coordinator
      port: 19530

    # Root coordinator
    rootCoord:
      address: milvus-root-coordinator
      port: 19530

    # Index coordinator
    indexCoord:
      address: milvus-index-coordinator
      port: 19530

    # Query coordinator
    queryCoord:
      address: milvus-query-coordinator
      port: 19530

    # Data node
    dataNode:
      port: 19530

    # Index node
    indexNode:
      port: 19530

    # Query node
    queryNode:
      port: 19530

    proxy:
      port: 19530
      accessLog:
        localPath: /dev
        filename: stdout
      http:
        enabled: true

    # Log configuration
    log:
      level: info
      stdout: true

    # Common configuration
    common:
      storageType: minio
      security:
        authorizationEnabled: false 