apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: milvus-base

resources:
  - namespace.yaml
  - secret-minio-credentials.yaml
  - secret-etcd-credentials.yaml
  - configmap.yaml
  - service.yaml
  - statefulset.yaml

commonLabels:
  app.kubernetes.io/name: milvus
  app.kubernetes.io/part-of: milvus 