apiVersion: v1
kind: Secret
metadata:
  name: milvus-minio-credentials
  namespace: milvus
  labels:
    app.kubernetes.io/name: milvus
    app.kubernetes.io/part-of: milvus
type: Opaque
data:
  accesskey: bWluaW9hZG1pbg==  # minioadmin
  secretkey: bWluaW9hZG1pbg==  # minioadmin 