apiVersion: v1
kind: Secret
metadata:
  name: milvus-etcd-credentials
  namespace: milvus
  labels:
    app.kubernetes.io/name: milvus
    app.kubernetes.io/part-of: milvus
type: Opaque
data:
  username: cm9vdA==  # root
  password: Y0JScHU4bUxFaw==  # cBRpu8mLEk 