# Milvus Proxy StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: milvus-proxy
  namespace: milvus
  labels:
    app.kubernetes.io/name: milvus
    app.kubernetes.io/component: proxy
spec:
  serviceName: milvus-headless
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: milvus
      app.kubernetes.io/component: proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: milvus
        app.kubernetes.io/component: proxy
    spec:
      containers:
      - name: milvus-proxy
        image: milvusdb/milvus:v2.4.0
        command: ["milvus"]
        args: ["run", "proxy"]
        ports:
        - containerPort: 19530
          name: grpc
        - containerPort: 19121
          name: http
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: milvus-minio-credentials
              key: accesskey
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: milvus-minio-credentials
              key: secretkey
        - name: ETCD_USERNAME
          valueFrom:
            secretKeyRef:
              name: milvus-etcd-credentials
              key: username
        - name: ETCD_PASSWORD
          valueFrom:
            secretKeyRef:
              name: milvus-etcd-credentials
              key: password
        volumeMounts:
        - name: milvus-config
          mountPath: /milvus/configs/milvus.yaml
          subPath: milvus.yaml
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: milvus-config
        configMap:
          name: milvus-config
---
# Milvus Root Coordinator StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: milvus-root-coordinator
  namespace: milvus
  labels:
    app.kubernetes.io/name: milvus
    app.kubernetes.io/component: root-coordinator
spec:
  serviceName: milvus-headless
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: milvus
      app.kubernetes.io/component: root-coordinator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: milvus
        app.kubernetes.io/component: root-coordinator
    spec:
      containers:
      - name: milvus-root-coordinator
        image: milvusdb/milvus:v2.4.0
        command: ["milvus"]
        args: ["run", "rootcoord"]
        ports:
        - containerPort: 19530
          name: grpc
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: milvus-minio-credentials
              key: accesskey
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: milvus-minio-credentials
              key: secretkey
        - name: ETCD_USERNAME
          valueFrom:
            secretKeyRef:
              name: milvus-etcd-credentials
              key: username
        - name: ETCD_PASSWORD
          valueFrom:
            secretKeyRef:
              name: milvus-etcd-credentials
              key: password
        volumeMounts:
        - name: milvus-config
          mountPath: /milvus/configs/milvus.yaml
          subPath: milvus.yaml
        - name: milvus-data
          mountPath: /var/lib/milvus
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: milvus-config
        configMap:
          name: milvus-config
      - name: milvus-data
        emptyDir: {}
---
# Milvus Data Coordinator StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: milvus-data-coordinator
  namespace: milvus
  labels:
    app.kubernetes.io/name: milvus
    app.kubernetes.io/component: data-coordinator
spec:
  serviceName: milvus-headless
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: milvus
      app.kubernetes.io/component: data-coordinator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: milvus
        app.kubernetes.io/component: data-coordinator
    spec:
      containers:
      - name: milvus-data-coordinator
        image: milvusdb/milvus:v2.4.0
        command: ["milvus"]
        args: ["run", "datacoord"]
        ports:
        - containerPort: 19530
          name: grpc
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: milvus-minio-credentials
              key: accesskey
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: milvus-minio-credentials
              key: secretkey
        - name: ETCD_USERNAME
          valueFrom:
            secretKeyRef:
              name: milvus-etcd-credentials
              key: username
        - name: ETCD_PASSWORD
          valueFrom:
            secretKeyRef:
              name: milvus-etcd-credentials
              key: password
        volumeMounts:
        - name: milvus-config
          mountPath: /milvus/configs/milvus.yaml
          subPath: milvus.yaml
        - name: milvus-data
          mountPath: /var/lib/milvus
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: milvus-config
        configMap:
          name: milvus-config
      - name: milvus-data
        emptyDir: {}
---
# Milvus Index Coordinator StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: milvus-index-coordinator
  namespace: milvus
  labels:
    app.kubernetes.io/name: milvus
    app.kubernetes.io/component: index-coordinator
spec:
  serviceName: milvus-headless
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: milvus
      app.kubernetes.io/component: index-coordinator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: milvus
        app.kubernetes.io/component: index-coordinator
    spec:
      containers:
      - name: milvus-index-coordinator
        image: milvusdb/milvus:v2.4.0
        command: ["milvus"]
        args: ["run", "indexcoord"]
        ports:
        - containerPort: 19530
          name: grpc
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: milvus-minio-credentials
              key: accesskey
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: milvus-minio-credentials
              key: secretkey
        - name: ETCD_USERNAME
          valueFrom:
            secretKeyRef:
              name: milvus-etcd-credentials
              key: username
        - name: ETCD_PASSWORD
          valueFrom:
            secretKeyRef:
              name: milvus-etcd-credentials
              key: password
        volumeMounts:
        - name: milvus-config
          mountPath: /milvus/configs/milvus.yaml
          subPath: milvus.yaml
        - name: milvus-data
          mountPath: /var/lib/milvus
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: milvus-config
        configMap:
          name: milvus-config
      - name: milvus-data
        emptyDir: {}
---
# Milvus Query Coordinator StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: milvus-query-coordinator
  namespace: milvus
  labels:
    app.kubernetes.io/name: milvus
    app.kubernetes.io/component: query-coordinator
spec:
  serviceName: milvus-headless
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: milvus
      app.kubernetes.io/component: query-coordinator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: milvus
        app.kubernetes.io/component: query-coordinator
    spec:
      containers:
      - name: milvus-query-coordinator
        image: milvusdb/milvus:v2.4.0
        command: ["milvus"]
        args: ["run", "querycoord"]
        ports:
        - containerPort: 19530
          name: grpc
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: milvus-minio-credentials
              key: accesskey
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: milvus-minio-credentials
              key: secretkey
        - name: ETCD_USERNAME
          valueFrom:
            secretKeyRef:
              name: milvus-etcd-credentials
              key: username
        - name: ETCD_PASSWORD
          valueFrom:
            secretKeyRef:
              name: milvus-etcd-credentials
              key: password
        volumeMounts:
        - name: milvus-config
          mountPath: /milvus/configs/milvus.yaml
          subPath: milvus.yaml
        - name: milvus-data
          mountPath: /var/lib/milvus
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: milvus-config
        configMap:
          name: milvus-config
      - name: milvus-data
        emptyDir: {}
---
# Milvus Data Node StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: milvus-data-node
  namespace: milvus
  labels:
    app.kubernetes.io/name: milvus
    app.kubernetes.io/component: data-node
spec:
  serviceName: milvus-headless
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: milvus
      app.kubernetes.io/component: data-node
  template:
    metadata:
      labels:
        app.kubernetes.io/name: milvus
        app.kubernetes.io/component: data-node
    spec:
      containers:
      - name: milvus-data-node
        image: milvusdb/milvus:v2.4.0
        command: ["milvus"]
        args: ["run", "datanode"]
        ports:
        - containerPort: 19530
          name: grpc
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: milvus-minio-credentials
              key: accesskey
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: milvus-minio-credentials
              key: secretkey
        - name: ETCD_USERNAME
          valueFrom:
            secretKeyRef:
              name: milvus-etcd-credentials
              key: username
        - name: ETCD_PASSWORD
          valueFrom:
            secretKeyRef:
              name: milvus-etcd-credentials
              key: password
        volumeMounts:
        - name: milvus-config
          mountPath: /milvus/configs/milvus.yaml
          subPath: milvus.yaml
        - name: milvus-data
          mountPath: /var/lib/milvus
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
      volumes:
      - name: milvus-config
        configMap:
          name: milvus-config
      - name: milvus-data
        emptyDir: {}
---
# Milvus Index Node StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: milvus-index-node
  namespace: milvus
  labels:
    app.kubernetes.io/name: milvus
    app.kubernetes.io/component: index-node
spec:
  serviceName: milvus-headless
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: milvus
      app.kubernetes.io/component: index-node
  template:
    metadata:
      labels:
        app.kubernetes.io/name: milvus
        app.kubernetes.io/component: index-node
    spec:
      containers:
      - name: milvus-index-node
        image: milvusdb/milvus:v2.4.0
        command: ["milvus"]
        args: ["run", "indexnode"]
        ports:
        - containerPort: 19530
          name: grpc
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: milvus-minio-credentials
              key: accesskey
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: milvus-minio-credentials
              key: secretkey
        - name: ETCD_USERNAME
          valueFrom:
            secretKeyRef:
              name: milvus-etcd-credentials
              key: username
        - name: ETCD_PASSWORD
          valueFrom:
            secretKeyRef:
              name: milvus-etcd-credentials
              key: password
        volumeMounts:
        - name: milvus-config
          mountPath: /milvus/configs/milvus.yaml
          subPath: milvus.yaml
        - name: milvus-data
          mountPath: /var/lib/milvus
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
      volumes:
      - name: milvus-config
        configMap:
          name: milvus-config
      - name: milvus-data
        emptyDir: {}
---
# Milvus Query Node StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: milvus-query-node
  namespace: milvus
  labels:
    app.kubernetes.io/name: milvus
    app.kubernetes.io/component: query-node
spec:
  serviceName: milvus-headless
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: milvus
      app.kubernetes.io/component: query-node
  template:
    metadata:
      labels:
        app.kubernetes.io/name: milvus
        app.kubernetes.io/component: query-node
    spec:
      containers:
      - name: milvus-query-node
        image: milvusdb/milvus:v2.4.0
        command: ["milvus"]
        args: ["run", "querynode"]
        ports:
        - containerPort: 19530
          name: grpc
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: milvus-minio-credentials
              key: accesskey
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: milvus-minio-credentials
              key: secretkey
        - name: ETCD_USERNAME
          valueFrom:
            secretKeyRef:
              name: milvus-etcd-credentials
              key: username
        - name: ETCD_PASSWORD
          valueFrom:
            secretKeyRef:
              name: milvus-etcd-credentials
              key: password
        volumeMounts:
        - name: milvus-config
          mountPath: /milvus/configs/milvus.yaml
          subPath: milvus.yaml
        - name: milvus-data
          mountPath: /var/lib/milvus
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
      volumes:
      - name: milvus-config
        configMap:
          name: milvus-config
      - name: milvus-data
        emptyDir: {} 