apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: triton
resources:
- service.yaml
- endpoints.yaml
labels:
- pairs:
    app.kubernetes.io/part-of: vllm
    app.kubernetes.io/name: vllm-external

