apiVersion: v1
kind: Service
metadata:
  name: vllm-external
  namespace: triton
  labels:
    app.kubernetes.io/name: vllm-external
    app.kubernetes.io/part-of: vllm
spec:
  selector: {}
  ports:
  - name: http
    port: 8003
    targetPort: 8003

