apiVersion: v1
kind: Endpoints
metadata:
  name: triton-external
  namespace: triton
subsets:
- addresses:
  - ip: 192.168.0.110
  ports:
  - name: http
    port: 8000
  - name: grpc
    port: 8001
  - name: metrics
    port: 8002

