apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-config
  namespace: postgres
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: config
data:
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres_password"
  POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
  POSTGRES_SHARED_PRELOAD_LIBRARIES: "pg_stat_statements"
  postgresql.conf: |
    # Connection settings
    listen_addresses = '*'
    port = 5432
    max_connections = 100
    
    # Allow all connections from Kubernetes cluster
    # This will be overridden by pg_hba.conf
    
    # Memory settings
    shared_buffers = 256MB
    effective_cache_size = 1GB
    maintenance_work_mem = 64MB
    work_mem = 4MB
    
    # WAL settings
    wal_buffers = 16MB
    checkpoint_completion_target = 0.9
    wal_writer_delay = 200ms
    
    # Query planner settings
    random_page_cost = 1.1
    effective_io_concurrency = 200
    
    # Logging
    log_destination = 'stderr'
    logging_collector = on
    log_directory = 'log'
    log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
    log_rotation_age = 1d
    log_rotation_size = 100MB
    log_min_duration_statement = 1000
    log_checkpoints = on
    log_connections = on
    log_disconnections = on
    log_lock_waits = on
    log_temp_files = -1
    log_autovacuum_min_duration = 0
    log_error_verbosity = verbose
    
    # Autovacuum
    autovacuum = on
    autovacuum_max_workers = 3
    autovacuum_naptime = 1min
    
    # Extensions
    shared_preload_libraries = 'pg_stat_statements'
    pg_stat_statements.track = all
    pg_stat_statements.max = 10000
  pg_hba.conf: |
    # TYPE  DATABASE        USER            ADDRESS                 METHOD
    # "local" is for Unix domain socket connections only
    local   all             all                                     trust
    # IPv4 local connections:
    host    all             all             127.0.0.1/32            trust
    # IPv6 local connections:
    host    all             all             ::1/128                 trust
    # Allow connections from Kubernetes cluster (10.42.0.0/16)
    host    all             all             10.42.0.0/16            md5
    # Allow connections from all other hosts
    host    all             all             0.0.0.0/0               md5 