apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: cloudnative-pg-staging

namespace: postgres

resources:
- ../../base

patches:
- target:
    kind: Cluster
    name: pg
  patch: |-
    - op: replace
      path: /spec/instances
      value: 2
    - op: replace
      path: /spec/resources/requests/memory
      value: "512Mi"
    - op: replace
      path: /spec/resources/requests/cpu
      value: "250m"
    - op: replace
      path: /spec/resources/limits/memory
      value: "1Gi"
    - op: replace
      path: /spec/resources/limits/cpu
      value: "1000m"
    - op: replace
      path: /spec/storage/size
      value: "20Gi"
- target:
    kind: Deployment
    name: adminer
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: "64Mi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: "25m"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: "128Mi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: "100m" 