apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: redis-base

resources:
- namespace.yaml
- configmap.yaml
- secret.yaml
- statefulset.yaml
- service.yaml
- redis-exporter.yaml

commonLabels:
  app.kubernetes.io/name: redis
  app.kubernetes.io/part-of: infrastructure 