apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: redis
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: infrastructure
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  - port: 26379
    targetPort: 26379
    protocol: TCP
    name: sentinel
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: infrastructure
---
apiVersion: v1
kind: Service
metadata:
  name: redis-external
  namespace: redis
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: infrastructure
spec:
  type: NodePort
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
    nodePort: 30379
  - port: 26379
    targetPort: 26379
    protocol: TCP
    name: sentinel
    nodePort: 30380
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: infrastructure 