apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: cloudnative-pg-dev

namespace: postgres

resources:
- ../../base

patches:
- target:
    kind: Cluster
    name: pg
  patch: |-
    - op: replace
      path: /spec/instances
      value: 1
    - op: replace
      path: /spec/resources/requests/memory
      value: "256Mi"
    - op: replace
      path: /spec/resources/requests/cpu
      value: "100m"
    - op: replace
      path: /spec/resources/limits/memory
      value: "512Mi"
    - op: replace
      path: /spec/resources/limits/cpu
      value: "500m"
- target:
    kind: Deployment
    name: pgadmin
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: "32Mi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: "10m"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: "64Mi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: "50m" 