apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: cloudnative-pg-base

resources:
- namespace.yaml
- secret.yaml
- cluster.yaml
- adminer.yaml
- ingress.yaml

commonLabels:
  app.kubernetes.io/name: cloudnative-pg
  app.kubernetes.io/part-of: infrastructure 