apiVersion: v1
kind: Secret
metadata:
  name: pg-app
  namespace: postgres
  labels:
    app.kubernetes.io/name: cloudnative-pg
    app.kubernetes.io/component: database
type: Opaque
stringData:
  username: postgres
  password: postgres_password 