apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: triton-model-repo
  namespace: triton
  labels:
    app.kubernetes.io/name: triton
    app.kubernetes.io/part-of: triton
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: fast-local-ssd

