apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: minio-selfsigned-clusterissuer
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: certificates
    app.kubernetes.io/part-of: infrastructure
spec:
  selfSigned: {} 