apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-internal-tls
  namespace: minio
spec:
  commonName: minio-hl.minio.svc.cluster.local
  dnsNames:
    # MinIO services
    - minio-hl.minio.svc.cluster.local
    - minio.minio.svc.cluster.local
    - minio-api.minio.svc.cluster.local
    - minio-console.minio.svc.cluster.local
    - minio-0.minio-hl.minio.svc.cluster.local
    - minio-1.minio-hl.minio.svc.cluster.local
    - minio-2.minio-hl.minio.svc.cluster.local
    - minio-3.minio-hl.minio.svc.cluster.local
    # etcd services
    - etcd.etcd.svc.cluster.local
    - etcd-headless.etcd.svc.cluster.local
    - etcd-0.etcd-headless.etcd.svc.cluster.local
    - etcd-1.etcd-headless.etcd.svc.cluster.local
    - etcd-2.etcd-headless.etcd.svc.cluster.local
    # Generic names
    - minio
    - etcd
    - localhost
    - '*.minio.svc.cluster.local'
    - '*.etcd.svc.cluster.local'
  duration: 2160h
  ipAddresses:
    - 127.0.0.1
    - ::1
  issuerRef:
    name: minio-internal-ca-issuer
    kind: Issuer
    group: cert-manager.io
  renewBefore: 360h
  secretName: minio-internal-tls
  subject:
    organizations:
      - Infrastructure
    organizationalUnits:
      - Internal TLS
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth 