apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-internal-ca
  namespace: minio
spec:
  isCA: true
  commonName: minio-internal-ca
  secretName: minio-internal-ca
  issuerRef:
    name: minio-selfsigned-clusterissuer
    kind: ClusterIssuer
    group: cert-manager.io 
  duration: 87600h
  renewBefore: 360h
  subject:
    organizations:
      - MinIO
    organizationalUnits:
      - MinIO Internal CA 