apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-internal-tls
  namespace: minio
spec:
  commonName: minio-hl.minio.svc.cluster.local
  dnsNames:
    - minio-hl.minio.svc.cluster.local
    - minio.minio.svc.cluster.local
    - minio-api.minio.svc.cluster.local
    - minio-console.minio.svc.cluster.local
    - minio
    - localhost
    - '*.minio.svc.cluster.local'
  duration: 2160h
  ipAddresses:
    - 127.0.0.1
    - ::1
  issuerRef:
    name: minio-internal-ca-issuer
    kind: Issuer
    group: cert-manager.io
  renewBefore: 360h
  secretName: minio-internal-tls
  subject:
    organizations:
      - MinIO
    organizationalUnits:
      - MinIO Internal TLS
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth 