apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-config
  namespace: minio
data:
  MINIO_DOMAIN: minio.askcollections.com
  MINIO_BROWSER_REDIRECT_URL: https://minio.askcollections.com
  MINIO_SERVER_URL: https://minio.askcollections.com 