apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-config
  namespace: minio
data:
  MINIO_SERVER_URL: "https://minio.askcollections.com"
  MINIO_CONSOLE_ADDRESS: ":9001"
  MINIO_API_SELECT_POOL: "on" 