apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-config
  namespace: minio
data:
  MINIO_DOMAIN: minio.askcollections.com
  MINIO_BROWSER_REDIRECT_URL: http://localhost:9001
  MINIO_SERVER_URL: http://minio-hl.minio.svc.cluster.local:9000