apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: minio
type: Opaque
data:
  # Default credentials (change these in production)
  # admin:Th1515T0p53cr3t (base64 encoded)
  access-key: YWRtaW4=
  secret-key: VGgxNTE1VDBwNTNjcjN0 