apiVersion: v1
kind: Secret
metadata:
  name: minio-access-all-buckets
  namespace: minio
type: Opaque
data:
  access-key: YWNjZXNzLWFsbC1idWNrZXRz
  secret-key: MEtsaGwrQzVkL1VzdVpxQUNxRWlDNGp3Nm16bEJodGU=

