apiVersion: v1
kind: Service
metadata:
  name: minio-console
  namespace: minio
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: console
spec:
  type: ClusterIP
  ports:
  - name: console
    port: 9001
    targetPort: 9001
    protocol: TCP
  selector:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: server 