apiVersion: v1
kind: Service
metadata:
  name: minio-console-service
  namespace: minio
spec:
  type: NodePort
  ports:
    - name: console
      port: 9001
      targetPort: 9001
      protocol: TCP
      nodePort: 30001
  selector:
    app.kubernetes.io/name: minio 