apiVersion: v1
kind: Service
metadata:
  name: minio-console
  namespace: minio
spec:
  type: NodePort
  ports:
    - name: console
      port: 9001
      targetPort: 9001
      nodePort: 30901
      protocol: TCP
  selector:
    app.kubernetes.io/name: minio 