apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: minio
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: server
spec:
  serviceName: minio-hl
  replicas: 4
  selector:
    matchLabels:
      app.kubernetes.io/name: minio
      app.kubernetes.io/component: server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minio
        app.kubernetes.io/component: server
    spec:
      containers:
      - name: minio
        image: minio/minio:RELEASE.2025-04-22T22-12-26Z
        command:
        - /bin/bash
        - -c
        args:
        - |
          # Generate distributed MinIO endpoints
          ENDPOINTS=""
          for i in $(seq 0 $((REPLICAS-1))); do
            ENDPOINTS="$ENDPOINTS http://minio-$i.minio-hl.minio.svc.cluster.local:9000/data"
          done
          
          # Start MinIO in distributed mode
          /usr/bin/minio server $ENDPOINTS --console-address :9001 --certs-dir /etc/minio/certs
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: access-key
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: secret-key
        - name: MINIO_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: minio-config
              key: MINIO_DOMAIN
        - name: MINIO_BROWSER_REDIRECT_URL
          valueFrom:
            configMapKeyRef:
              name: minio-config
              key: MINIO_BROWSER_REDIRECT_URL
        - name: MINIO_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: minio-config
              key: MINIO_SERVER_URL
        - name: REPLICAS
          value: "4"
        ports:
        - containerPort: 9000
          name: api
        - containerPort: 9001
          name: console
        volumeMounts:
        - name: data
          mountPath: /data
        - name: tls-certs
          mountPath: /etc/minio/certs
          readOnly: true
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
            scheme: HTTPS
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /minio/health/ready
            port: 9000
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
      volumes:
      - name: tls-certs
        secret:
          secretName: minio-internal-tls
          items:
          - key: tls.crt
            path: public.crt
          - key: tls.key
            path: private.key
          - key: ca.crt
            path: CAs/ca.crt
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: nfs-client
      resources:
        requests:
          storage: 50Gi 